baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'Hugo theme JIRA issues'

[menus]
  [[menus.main]]
    name = 'projects'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'labels'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = 'fix versions'
    pageRef = '/fix_versions'
    weight = 31

  [[menus.main]]
    name = 'affected versions'
    pageRef = '/affected_versions'
    weight = 32

[outputFormats.sidebar]
  mediaType = "text/html"
  baseName = "sidebar"
  isHTML = true
  notAlternative = true

[outputFormats.rawmd]
  mediaType = "text/plain"
  baseName = "raw"
  isPlainText = true
  notAlternative = true

[outputs]
  section = ["html", "sidebar"]
  page = ["html", "rawmd"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    style = 'tango'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
